AWSTemplateFormatVersion: '2010-09-09'
Description: A starter AWS Lambda function. Test lambda function for the scotty1 bot.
Parameters:
  Channel:
    Default: ''
    Type: String
  HookUrl:
    Default: ''
    Type: String
  IntentName:
    Default: ''
    Type: String
  apiToken:
    Default: ''
    Type: String
  groups:
    Default: ''
    Type: String
Resources:
  ExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogStreams
            - iam:AttachGroupPolicy
            - iam:AttachUserPolicy
            - iam:ListGroupsForUser
            - dynamodb:ListTables
            - iam:CreatePolicy
            - iam:GetPolicy
            - lambda:InvokeFunction
            - iam:GetPolicyVersion
            - iam:CreatePolicyVersion
            - iam:ListPolicyVersions
            - iam:DeletePolicyVersion
            - lambda:GetFunctionConfiguration
            - lambda:RemovePermission
            - iam:ListAttachedGroupPolicies
            Effect: Allow
            Resource:
            - '*'
          - Action:
            - dynamodb:*
            Effect: Allow
            Resource:
            - Fn::Join:
              - ''
              - - 'arn:aws:dynamodb:'
                - Ref: AWS::Region
                - ':'
                - Ref: AWS::AccountId
                - :table/ScottyTable
          Version: '2012-10-17'
        PolicyName: AllowIAMPolicyModifications
    Type: AWS::IAM::Role
  ScottyTable:
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
      - AttributeName: KEY
        AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      - AttributeName: KEY
        KeyType: HASH
      TableName: ScottyTable
    Type: AWS::DynamoDB::Table
  TableAccess:
    LambdaInvokePermission:
      Properties:
        Action: lambda:InvokeFunction
        FunctionName:
          Fn::GetAtt:
          - TableAccess
          - Arn
        Principal: events.amazonaws.com
        SourceArn:
          Fn::Join:
          - ''
          - - 'arn:aws:lex:'
            - Ref: AWS::Region
            - ':'
            - Ref: AWS::AccountId
            - ':intent:'
            - Ref: IntentName
            - :*
      Type: AWS::Lambda::Permission
    Properties:
      CodeUri: s3://dev2-useast1-lambda-deploy/TableAccess/bc2d25f86bfb3c17eace501711649b5a
      Description: Table Access
      Environment:
        Variables:
          DYNAMODB_TABLE: Scotty-Table
          GroupName:
            Ref: groups
          HookUrl:
            Ref: HookUrl
          api_token:
            Ref: apiToken
          notificationChannel:
            Ref: Channel
      FunctionName: Scotty-TableAccessTest
      Handler: LambdaHandler.lambda_handler
      MemorySize: 128
      Role:
        Fn::GetAtt:
        - ExecutionRole
        - Arn
      Runtime: python3.6
      Timeout: 30
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
